import "./globals.css";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { EdgeStoreProvider } from "../lib/edgestore";
import { ThemeProvider } from "@/components/providers/themeprovider";
import { UiPreferencesProvider } from "@/components/providers/ui-preferences";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Toaster } from "@/components/ui/sonner"
import MyTopBar from "@/components/uicustom/topbar";

/** NEW: one client wrapper that contains ActiveNetwork + wagmi + react-query + Solana + WalletContext + Pricing */
import Web3Providers from "@/components/crypto-related/Web3Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await auth();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} myanimation transition-colors h-full`} suppressHydrationWarning={true}>
        <SessionProvider session={session} refetchOnWindowFocus={true}>
          <EdgeStoreProvider>
            <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
              <UiPreferencesProvider>
                <Web3Providers>

                  <MyTopBar />
                  {children}
                  <Toaster />
                </Web3Providers>
              </UiPreferencesProvider>
              <SpeedInsights />
            </ThemeProvider>
          </EdgeStoreProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
