import "./globals.css";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { EdgeStoreProvider } from '../lib/edgestore';
import { ThemeProvider } from "@/components/providers/themeprovider";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

import { Toaster } from "@/components/ui/sonner";
import MyTopBar from "@/components/uicustom/topbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const LOG_PREFIX = '[layout.tsx]'
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} myamination transition-colors h-full`} suppressHydrationWarning={true}>
        <SessionProvider session={session}>
          <EdgeStoreProvider>
            <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange >
              <Toaster />
              <MyTopBar />
              {children}
            </ThemeProvider>
          </EdgeStoreProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
