'use server';

import { auth } from '@/auth';
import { dbPrisma } from "@/lib/db";
import { MyProductCreateSchema, type CategoryTag } from "@/schemas";
import { FiatCurrency, Prisma } from "@/generated/prisma/browser";
import { z } from "zod";
import { createSlug } from "@/lib/category-utils";
import crypto from "crypto";
import { revalidatePath } from "next/cache";

type CreateProductResult = { error: string } | { success: string; productId: string };
type UpdateProductResult = { error: string } | { success: string };
type EnsureOwnerTestProductResult =
  | { error: string }
  | { success: string; productId: string; created: boolean };

const OWNER_TEST_PRODUCT_TITLE = 'Veggat Digital Checkout Test';
const OWNER_TEST_PRODUCT_CATEGORY = 'Digital Downloads';
const OWNER_TEST_PRODUCT_CONTENT = [
  'Veggat checkout test download',
  '',
  'If you can read this after payment, the digital product delivery path worked.',
  `Generated by Veggat on ${new Date('2026-06-19T00:00:00.000Z').toISOString().slice(0, 10)}.`,
].join('\n');
const OWNER_TEST_PRODUCT_BUFFER = Buffer.from(OWNER_TEST_PRODUCT_CONTENT, 'utf8');
const OWNER_TEST_PRODUCT_STORAGE_KEY = `data:text/plain;charset=utf-8;base64,${OWNER_TEST_PRODUCT_BUFFER.toString('base64')}`;
const OWNER_TEST_PRODUCT_CHECKSUM = crypto
  .createHash('sha256')
  .update(OWNER_TEST_PRODUCT_BUFFER)
  .digest('hex');

const ProductAcceptedTokenInputSchema = z
  .object({
    family: z.enum(['EVM', 'SOLANA']),
    symbol: z.string().min(1).max(32),
    decimals: z.number().int().nonnegative().max(255),
    tokenAddress: z.string().trim().min(1).max(200).nullable().optional(),
    tokenMint: z.string().trim().min(1).max(200).nullable().optional(),
  })
  .strict();

const SpecificationInputSchema = z
  .object({
    key: z.string().min(1).max(200),
    value: z.union([z.string().max(2000), z.number().finite()]),
  })
  .strict();

const FeatureInputSchema = z
  .object({
    text: z.string().min(1).max(500),
    key: z.string().max(100).optional(),
    icon: z.string().max(50).optional(),
  })
  .strict();

const ProductUpdatePatchSchema = z
  .object({
    title: z.string().trim().min(1).max(200).optional(),
    description: z.string().trim().min(1).max(8000).optional(),
    category: z.string().trim().min(1).max(200).optional(),
    price: z.number().finite().optional(),
    priceCurrency: z.enum(['USD', 'NOK', 'EUR', 'GBP']).optional(),
    acceptedFiatCurrencies: z.array(z.enum(['USD', 'NOK', 'EUR', 'GBP'])).optional(),
    condition: z.enum(['NEW', 'AS_NEW', 'GOOD', 'FAIR', 'POOR']).optional(),
    stock: z.number().int().min(0).max(1_000_000).optional(),
    shipFromPostalId: z.string().trim().min(0).max(2000).optional(),
    image: z.array(z.string().trim().min(1).max(4000)).max(20).optional(),
    specifications: z.array(SpecificationInputSchema).max(200).optional(),
    features: z.array(FeatureInputSchema).max(50).optional(),
    acceptedTokens: z.array(ProductAcceptedTokenInputSchema).optional(),
  })
  .strict();

// Helper: Handle categories - create new ones or link existing ones
async function handleCategories(
  productId: string,
  categories: CategoryTag[],
  userId: string
): Promise<void> {
  if (!categories || categories.length === 0) return;

  for (const cat of categories) {
    let categoryId = cat.id;

    // If it's a new category (no ID), create it
    if (!categoryId || cat.isNew) {
      const slug = createSlug(cat.name);
      
      // Check if category with this slug already exists
      const existing = await dbPrisma.category.findUnique({
        where: { slug },
      });

      if (existing) {
        categoryId = existing.id;
      } else {
        // Create new category
        const newCategory = await dbPrisma.category.create({
          data: {
            name: cat.name.trim(),
            slug,
            parentId: cat.parentId || null,
            createdById: userId,
          },
        });
        categoryId = newCategory.id;
      }
    }

    // Link category to product
    await dbPrisma.productCategory.create({
      data: {
        productId,
        categoryId,
      },
    });
  }
}

export const ensureOwnerCheckoutTestProductAction = async (): Promise<EnsureOwnerTestProductResult> => {
  try {
    const session = await auth();
    if (!session?.user?.id) {
      return { error: 'Unauthorized - sign in with the owner account first.' };
    }

    if (session.user.role !== 'OWNER') {
      return { error: 'Only the platform owner can create the production checkout test product.' };
    }

    const sessionUserId = session.user.id;
    const now = new Date();

    const { product, created } = await dbPrisma.$transaction(async (tx) => {
      const digitalAsset = await tx.digitalAsset.upsert({
        where: { storageKey: OWNER_TEST_PRODUCT_STORAGE_KEY },
        update: {
          fileName: 'veggat-checkout-test.txt',
          fileSize: OWNER_TEST_PRODUCT_BUFFER.byteLength,
          mimeType: 'text/plain',
          fileExtension: 'txt',
          storageProvider: 'LOCAL',
          checksum: OWNER_TEST_PRODUCT_CHECKSUM,
          uploadedById: sessionUserId,
          companyId: null,
          isActive: true,
        },
        create: {
          fileName: 'veggat-checkout-test.txt',
          fileSize: OWNER_TEST_PRODUCT_BUFFER.byteLength,
          mimeType: 'text/plain',
          fileExtension: 'txt',
          storageKey: OWNER_TEST_PRODUCT_STORAGE_KEY,
          storageProvider: 'LOCAL',
          checksum: OWNER_TEST_PRODUCT_CHECKSUM,
          uploadedById: sessionUserId,
          companyId: null,
          isActive: true,
        },
      });

      const existingByAsset = await tx.product.findFirst({
        where: { digitalAssetId: digitalAsset.id },
      });
      const existingByOwnerTitle = existingByAsset
        ? null
        : await tx.product.findFirst({
            where: {
              userId: sessionUserId,
              title: OWNER_TEST_PRODUCT_TITLE,
              productType: 'DIGITAL',
            },
          });
      const existingProduct = existingByAsset ?? existingByOwnerTitle;

      const productData = {
        title: OWNER_TEST_PRODUCT_TITLE,
        description:
          'Low-cost production checkout test item for validating PayPal, crypto wallet checkout, receipt emails, stock updates, and digital download delivery.',
        category: OWNER_TEST_PRODUCT_CATEGORY,
        condition: 'NEW' as const,
        price: 1,
        priceCurrency: FiatCurrency.USD,
        acceptedFiatCurrencies: [FiatCurrency.USD],
        stock: 25,
        shipFromPostalId: 'Digital delivery',
        image: [
          'https://picsum.photos/seed/veggat-digital-checkout/800/800',
          'https://picsum.photos/seed/veggat-download-ready/800/800',
        ],
        specifications: [
          { key: 'Fulfilment', value: 'Automatic digital delivery' },
          { key: 'Purpose', value: 'Production checkout smoke test' },
          { key: 'Price', value: '1 USD' },
        ],
        features: [
          { text: 'Digital-only product with no shipping requirement' },
          { text: 'Generates download tokens after payment completion' },
          { text: 'Safe low-price item for real end-to-end checkout testing' },
        ],
        userId: sessionUserId,
        companyId: null,
        receiverWalletId: null,
        productType: 'DIGITAL' as const,
        digitalAssetId: digitalAsset.id,
        downloadsEnabled: true,
        maxDownloads: 5,
        downloadExpiryDays: 30,
        freeShippingEnabled: false,
        freeShippingThreshold: null,
        updatedAt: now,
      };

      const product = existingProduct
        ? await tx.product.update({
            where: { id: existingProduct.id },
            data: productData,
          })
        : await tx.product.create({
            data: {
              ...productData,
              createdAt: now,
            },
          });

      await tx.productAcceptedToken.upsert({
        where: {
          productId_family_symbol: {
            productId: product.id,
            family: 'EVM',
            symbol: 'ETH',
          },
        },
        update: { decimals: 18, tokenAddress: null, tokenMint: null },
        create: {
          productId: product.id,
          family: 'EVM',
          symbol: 'ETH',
          decimals: 18,
          tokenAddress: null,
          tokenMint: null,
        },
      });

      await tx.productAcceptedToken.upsert({
        where: {
          productId_family_symbol: {
            productId: product.id,
            family: 'EVM',
            symbol: 'PLS',
          },
        },
        update: { decimals: 18, tokenAddress: null, tokenMint: null },
        create: {
          productId: product.id,
          family: 'EVM',
          symbol: 'PLS',
          decimals: 18,
          tokenAddress: null,
          tokenMint: null,
        },
      });

      await tx.productAcceptedToken.upsert({
        where: {
          productId_family_symbol: {
            productId: product.id,
            family: 'SOLANA',
            symbol: 'SOL',
          },
        },
        update: { decimals: 9, tokenAddress: null, tokenMint: null },
        create: {
          productId: product.id,
          family: 'SOLANA',
          symbol: 'SOL',
          decimals: 9,
          tokenAddress: null,
          tokenMint: null,
        },
      });

      const categorySlug = createSlug(OWNER_TEST_PRODUCT_CATEGORY);
      const category = await tx.category.upsert({
        where: { slug: categorySlug },
        update: {
          name: OWNER_TEST_PRODUCT_CATEGORY,
          description: 'Downloadable products and checkout test listings.',
        },
        create: {
          name: OWNER_TEST_PRODUCT_CATEGORY,
          slug: categorySlug,
          description: 'Downloadable products and checkout test listings.',
          createdById: sessionUserId,
        },
      });

      await tx.productCategory.upsert({
        where: {
          productId_categoryId: {
            productId: product.id,
            categoryId: category.id,
          },
        },
        update: {},
        create: {
          productId: product.id,
          categoryId: category.id,
        },
      });

      return { product, created: !existingProduct };
    });

    revalidatePath('/products');
    revalidatePath('/api/products');
    revalidatePath(`/products/${product.id}`);

    return {
      success: created
        ? 'Checkout test product created and listed.'
        : 'Checkout test product refreshed and kept available.',
      productId: product.id,
      created,
    };
  } catch (error) {
    console.error('[products] Failed to ensure owner checkout test product:', error);
    return { error: 'Failed to create the checkout test product.' };
  }
};

export const MyCreateProductAction = async (data: z.infer<typeof MyProductCreateSchema>, postalCodes: string[]): Promise<CreateProductResult> => {
  try {
    // --- AUTH CHECK (CRITICAL) ---
    const session = await auth();
    if (!session?.user?.id) {
      return { error: 'Unauthorized — you must be logged in to create a product.' };
    }
    const sessionUserId = session.user.id;

    console.log('Server is Creating a product with data: ', data);
    const validatedData = MyProductCreateSchema.parse(data);

    // Override client-supplied userId with verified session user
    // (prevents IDOR — callers cannot create products as another user)
    if (validatedData.userId !== sessionUserId) {
      console.warn(`[products] userId mismatch: client sent ${validatedData.userId}, session is ${sessionUserId}. Overriding.`);
    }

    // Verify companyId ownership — if a company is specified, the caller must be OWNER/MANAGER/employee
    if (validatedData.companyId) {
      const employee = await dbPrisma.employee.findFirst({
        where: {
          userId: sessionUserId,
          companyId: validatedData.companyId,
        },
      });
      const company = await dbPrisma.company.findUnique({
        where: { id: validatedData.companyId },
        select: { ownerId: true },
      });
      if (!employee && company?.ownerId !== sessionUserId) {
        return { error: 'You do not have permission to create products for this company.' };
      }
    }

    const cleanedPostalCodes = Array.from(
      new Set((postalCodes ?? []).map((p) => p.trim()).filter(Boolean))
    );

    // Check if this product needs physical shipping
    const needsShipping = validatedData.productType === 'PHYSICAL' || validatedData.productType === 'HYBRID';

    // Server-side guard: company listings with physical logistics must have at least one warehouse.
    if (needsShipping && validatedData.companyId) {
      const warehouseCount = await dbPrisma.warehouseLocation.count({
        where: { companyId: validatedData.companyId },
      });

      if (warehouseCount === 0) {
        return {
          error:
            'This company needs a warehouse address before creating physical or hybrid products. Add one in Company Settings and try again.',
        };
      }
    }
    
    if (needsShipping && cleanedPostalCodes.length === 0) {
      return { error: 'Please add at least one ship-from postal code for a physical product.' };
    }

    // Check if digital product has an asset
    const needsDigitalAsset = validatedData.productType === 'DIGITAL' || validatedData.productType === 'HYBRID';
    if (needsDigitalAsset && !validatedData.digitalAssetId) {
      return { error: 'Digital products require a digital asset file.' };
    }

    const product = await dbPrisma.product.create({
      data: {
        title: validatedData.title,
        description: validatedData.description,
        category: validatedData.category,
        condition: validatedData.condition ?? 'NEW',
        price: validatedData.price,
        priceCurrency: (validatedData as any).priceCurrency ?? 'USD',
        acceptedFiatCurrencies: (() => {
          const pc = ((validatedData as any).priceCurrency ?? 'USD') as string;
          const list = Array.isArray((validatedData as any).acceptedFiatCurrencies)
            ? ((validatedData as any).acceptedFiatCurrencies as string[])
            : [];
          const normalized = Array.from(new Set(list.filter(Boolean)));
          return normalized.length ? (normalized as any) : ([pc] as any);
        })(),
        stock: validatedData.quantity,
        shipFromPostalId: validatedData.shipFromPostalId ?? cleanedPostalCodes.join(', '),
        image: validatedData.image,
        specifications: validatedData.specifications ? JSON.stringify(validatedData.specifications) : Prisma.JsonNull,
        features: validatedData.features ? JSON.stringify(validatedData.features) : Prisma.JsonNull,
        userId: sessionUserId,
        companyId: validatedData.companyId ?? null,
        // Digital product fields
        productType: validatedData.productType ?? 'PHYSICAL',
        digitalAssetId: validatedData.digitalAssetId ?? null,
        downloadsEnabled: validatedData.downloadsEnabled ?? true,
        maxDownloads: validatedData.maxDownloads ?? null,
        downloadExpiryDays: validatedData.downloadExpiryDays ?? null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    });

    console.log('Product created: ', product);

    // Handle categories - create new ones and link to product
    if (validatedData.categories && validatedData.categories.length > 0) {
      await handleCategories(product.id, validatedData.categories, sessionUserId);
      console.log('Categories linked: ', validatedData.categories.map(c => c.name).join(', '));
    }

    // Handle crypto accepted tokens
    const rawTokens = (validatedData as any).acceptedTokens;
    if (Array.isArray(rawTokens) && rawTokens.length > 0) {
      for (const t of rawTokens) {
        const parsed = ProductAcceptedTokenInputSchema.safeParse(t);
        if (!parsed.success) continue;
        await dbPrisma.productAcceptedToken.create({
          data: {
            productId: product.id,
            family: parsed.data.family as any,
            symbol: parsed.data.symbol.toUpperCase().trim(),
            decimals: parsed.data.decimals,
            tokenAddress: parsed.data.tokenAddress ?? null,
            tokenMint: parsed.data.tokenMint ?? null,
          },
        });
      }
      console.log('Accepted tokens: ', rawTokens.map((t: any) => t.symbol).join(', '));
    }

    // Handle receiver wallet assignment
    const receiverWalletId = (validatedData as any).receiverWalletId;
    if (receiverWalletId && typeof receiverWalletId === 'string') {
      await dbPrisma.product.update({
        where: { id: product.id },
        data: { receiverWalletId },
      });
    }

    // Skip warehouse/inventory setup for digital-only products
    if (!needsShipping || cleanedPostalCodes.length === 0) {
      return { success: 'Product created successfully.', productId: product.id };
    }

    const quantityPerWarehouse = Math.floor(validatedData.quantity / cleanedPostalCodes.length);
    const remainder = validatedData.quantity % cleanedPostalCodes.length;

    console.log('Quantity per warehouse: ', quantityPerWarehouse, ' Remainder: ', remainder);

    for (let i = 0; i < cleanedPostalCodes.length; i++) {
      const postalCode = cleanedPostalCodes[i];
      
      let warehouse = await dbPrisma.warehouseLocation.findFirst({
        where: { postalCode },
      });

      if (!warehouse) {
        warehouse = await dbPrisma.warehouseLocation.create({
          data: {
            postalCode,
            address: '',
            city: '',
            country: 'Norway',
            userId: sessionUserId,
            companyId: validatedData.companyId ?? null,
          },
        });
      }

      console.log('Warehouse for postal code ', postalCode, ': ', warehouse);

      const inventory = await dbPrisma.inventory.create({
        data: {
          quantity: i === 0 ? quantityPerWarehouse + remainder : quantityPerWarehouse,
          stock: i === 0 ? quantityPerWarehouse + remainder : quantityPerWarehouse,
          warehouseId: warehouse.id,
          productId: product.id,
        },
      });

      console.log('Inventory created: ', inventory);
    }

    return { success: "Product created successfully with inventory distributed among warehouses.", productId: product.id };
  } catch (error) {
    console.error('Error creating product: ', error);
    return { error: "Failed to create product." };
  }
};

export const MyUpdateProductAction = async (
  productId: string,
  patch: z.infer<typeof ProductUpdatePatchSchema>
): Promise<UpdateProductResult> => {
  try {
    const session = await auth();
    const sessionUserId = session?.user?.id;
    const role = session?.user?.role;
    if (!sessionUserId) {
      return { error: 'Unauthorized' };
    }

    const parsedPatch = ProductUpdatePatchSchema.safeParse(patch);
    if (!parsedPatch.success) {
      return { error: 'Invalid update payload' };
    }

    const product = await dbPrisma.product.findUnique({
      where: { id: productId },
      select: { 
        id: true, 
        userId: true, 
        companyId: true,
        Company: { select: { ownerId: true } },
      },
    });

    if (!product) return { error: 'Product not found' };

    const isAdminLike = role === 'ADMIN' || role === 'OWNER';
    const isProductOwner = product.userId === sessionUserId;
    const isCompanyOwner = product.Company?.ownerId === sessionUserId;
    let allowed = isAdminLike || isProductOwner || isCompanyOwner;

    // Check employee permissions if not already allowed
    if (!allowed && product.companyId) {
      const employee = await dbPrisma.employee.findFirst({
        where: { userId: sessionUserId, companyId: product.companyId },
        select: { permissions: true },
      });

      const p: any = employee?.permissions ?? {};
      const canEdit = p?.CAN_EDIT_PRODUCT_POSITION_PERMISSION === true;
      allowed = canEdit;
    }

    if (!allowed) {
      return { error: 'Forbidden' };
    }

    const acceptedTokens = parsedPatch.data.acceptedTokens;

    await dbPrisma.$transaction(async (tx) => {
      const nextPriceCurrency = (parsedPatch.data.priceCurrency ?? undefined) as any;
        const nextAcceptedFiatCurrencies = Array.isArray(parsedPatch.data.acceptedFiatCurrencies)
          ? parsedPatch.data.acceptedFiatCurrencies
          : undefined;

        const acceptedFiatCurrenciesPatched = (() => {
          if (!nextAcceptedFiatCurrencies) return undefined;
          const normalized = Array.from(new Set(nextAcceptedFiatCurrencies.filter(Boolean)));
          if (normalized.length) return normalized;
          if (nextPriceCurrency) return [nextPriceCurrency];
          return undefined;
        })();

      const specificationsPatched = (() => {
        if (!Array.isArray(parsedPatch.data.specifications)) return undefined;
        return JSON.stringify(parsedPatch.data.specifications);
      })();

      const featuresPatched = (() => {
        if (!Array.isArray(parsedPatch.data.features)) return undefined;
        return JSON.stringify(parsedPatch.data.features);
      })();

      const shouldUpdateProduct =
        typeof parsedPatch.data.title === 'string' ||
        typeof parsedPatch.data.description === 'string' ||
        typeof parsedPatch.data.category === 'string' ||
        typeof parsedPatch.data.price === 'number' ||
        typeof parsedPatch.data.priceCurrency === 'string' ||
        Boolean(acceptedFiatCurrenciesPatched) ||
        typeof parsedPatch.data.condition === 'string' ||
        typeof parsedPatch.data.stock === 'number' ||
        typeof parsedPatch.data.shipFromPostalId === 'string' ||
        Array.isArray(parsedPatch.data.image) ||
        typeof specificationsPatched === 'string' ||
        typeof featuresPatched === 'string';

      if (shouldUpdateProduct) {

        await tx.product.update({
          where: { id: productId },
          data: {
            ...(typeof parsedPatch.data.title === 'string' ? { title: parsedPatch.data.title } : {}),
            ...(typeof parsedPatch.data.description === 'string' ? { description: parsedPatch.data.description } : {}),
            ...(typeof parsedPatch.data.category === 'string' ? { category: parsedPatch.data.category } : {}),
            ...(typeof parsedPatch.data.price === 'number' ? { price: parsedPatch.data.price } : {}),
            ...(typeof parsedPatch.data.priceCurrency === 'string' ? { priceCurrency: parsedPatch.data.priceCurrency as any } : {}),
            ...(acceptedFiatCurrenciesPatched ? { acceptedFiatCurrencies: acceptedFiatCurrenciesPatched as any } : {}),
            ...(typeof parsedPatch.data.condition === 'string' ? { condition: parsedPatch.data.condition as any } : {}),
            ...(typeof parsedPatch.data.stock === 'number' ? { stock: parsedPatch.data.stock } : {}),
            ...(typeof parsedPatch.data.shipFromPostalId === 'string' ? { shipFromPostalId: parsedPatch.data.shipFromPostalId } : {}),
            ...(Array.isArray(parsedPatch.data.image) ? { image: parsedPatch.data.image } : {}),
            ...(typeof specificationsPatched === 'string' ? { specifications: specificationsPatched as any } : {}),
            ...(typeof featuresPatched === 'string' ? { features: featuresPatched as any } : {}),
          },
        });
      }

      if (acceptedTokens) {
        const normalized = acceptedTokens.map((t) => ({
          family: t.family,
          symbol: t.symbol.toUpperCase().trim(),
          decimals: t.decimals,
          tokenAddress: t.tokenAddress ?? null,
          tokenMint: t.tokenMint ?? null,
        }));

        // delete tokens not present anymore
        const keep = new Set(normalized.map((t) => `${t.family}:${t.symbol}`));
        const existing = await tx.productAcceptedToken.findMany({
          where: { productId },
          select: { id: true, family: true, symbol: true },
        });

        const toDelete = existing
          .filter((e) => !keep.has(`${e.family}:${e.symbol}`))
          .map((e) => e.id);

        if (toDelete.length) {
          await tx.productAcceptedToken.deleteMany({ where: { id: { in: toDelete } } });
        }

        // upsert current list
        for (const t of normalized) {
          await tx.productAcceptedToken.upsert({
            where: {
              productId_family_symbol: {
                productId,
                family: t.family as any,
                symbol: t.symbol,
              },
            },
            create: {
              productId,
              family: t.family as any,
              symbol: t.symbol,
              decimals: t.decimals,
              tokenAddress: t.tokenAddress,
              tokenMint: t.tokenMint,
            },
            update: {
              decimals: t.decimals,
              tokenAddress: t.tokenAddress,
              tokenMint: t.tokenMint,
            },
          });
        }
      }
    });

    return { success: 'Product updated successfully.' };
  } catch (error) {
    console.error('Error updating product: ', error);
    return { error: 'Failed to update product.' };
  }
};

/**
 * Delete a product (requires ownership or company permission)
 */
export const MyDeleteProductAction = async (productId: string) => {
  try {
    const session = await auth();
    if (!session?.user?.id) {
      return { error: 'Unauthorized' };
    }

    const sessionUserId = session.user.id;
    const role = session.user.role;

    const product = await dbPrisma.product.findUnique({
      where: { id: productId },
      select: { 
        id: true, 
        userId: true, 
        companyId: true, 
        title: true,
        Company: { select: { ownerId: true } },
      },
    });

    if (!product) {
      return { error: 'Product not found' };
    }

    // Check permissions
    const isAdminLike = role === 'ADMIN' || role === 'OWNER';
    const isProductOwner = product.userId === sessionUserId;
    const isCompanyOwner = product.Company?.ownerId === sessionUserId;
    let allowed = isAdminLike || isProductOwner || isCompanyOwner;

    // Check employee permissions if not already allowed
    if (!allowed && product.companyId) {
      const employee = await dbPrisma.employee.findFirst({
        where: { userId: sessionUserId, companyId: product.companyId },
        select: { permissions: true },
      });

      const p: any = employee?.permissions ?? {};
      // Can delete if they have delete product permission OR edit product permission (backwards compat)
      const canDelete = p?.CAN_DELETE_PRODUCT === true || p?.CAN_EDIT_PRODUCT_POSITION_PERMISSION === true;
      allowed = canDelete;
    }

    if (!allowed) {
      return { error: 'Forbidden - You do not have permission to delete this product' };
    }

    // Delete in transaction (cascade deletes related records)
    await dbPrisma.$transaction(async (tx) => {
      // Delete accepted tokens
      await tx.productAcceptedToken.deleteMany({
        where: { productId },
      });

      // Delete inventory records
      await tx.inventory.deleteMany({
        where: { productId },
      });

      // Delete the product
      await tx.product.delete({
        where: { id: productId },
      });
    });

    return { success: `Product "${product.title}" deleted successfully.` };
  } catch (error) {
    console.error('Error deleting product: ', error);
    return { error: 'Failed to delete product.' };
  }
};
