/**
 * @fileOverview Aggregates JSDoc-style context tags from source files into MasterContext.md
 * @stability experimental
 * @decisions TypeScript script runnable via ts-node; extracts @fileOverview, @stability,
 *   @dependencies, @crossReferences, @keyInvariants, @decisions tags from all .ts/.tsx files
 *
 * Usage:
 *   npx ts-node scripts/aggregate-context.ts
 *   npx ts-node scripts/aggregate-context.ts --dry-run   (preview without writing)
 *
 * This script:
 * 1. Walks frontend/src, frontend/app, frontend/actions, frontend/components, frontend/lib,
 *    frontend/hooks, frontend/contexts, frontend/schemas, and backend/src
 * 2. Extracts tagged JSDoc comments from each file
 * 3. Generates a "Module Annotations" section
 * 4. Appends/replaces the auto-generated section in MasterContext.md
 */

import * as fs from "fs";
import * as path from "path";

// ─── Configuration ───────────────────────────────────────────────────────────

const ROOT = path.resolve(__dirname, "..");
const MASTER_CONTEXT_PATH = path.join(ROOT, "MasterContext.md");

const SCAN_DIRS = [
  "frontend/app",
  "frontend/actions",
  "frontend/components",
  "frontend/contexts",
  "frontend/hooks",
  "frontend/lib",
  "frontend/schemas",
  "backend/src",
];

const FILE_EXTENSIONS = [".ts", ".tsx"];

const TAGS = [
  "fileOverview",
  "stability",
  "dependencies",
  "crossReferences",
  "keyInvariants",
  "decisions",
] as const;

type TagName = (typeof TAGS)[number];

interface FileContext {
  relativePath: string;
  tags: Partial<Record<TagName, string>>;
}

// ─── Tag Extraction ──────────────────────────────────────────────────────────

function extractTags(content: string): Partial<Record<TagName, string>> {
  const tags: Partial<Record<TagName, string>> = {};

  for (const tag of TAGS) {
    // Match @tag followed by content until next @tag or end of comment block
    const regex = new RegExp(
      `@${tag}\\s+([\\s\\S]*?)(?=@(?:${TAGS.join("|")})|\\*\\/|$)`,
      "m"
    );
    const match = content.match(regex);
    if (match) {
      tags[tag] = match[1]
        .replace(/^\s*\*\s?/gm, "") // strip leading * from JSDoc lines
        .replace(/\s+/g, " ") // collapse whitespace
        .trim();
    }
  }

  return tags;
}

// ─── File Walking ────────────────────────────────────────────────────────────

function walkDir(dir: string): string[] {
  const results: string[] = [];
  if (!fs.existsSync(dir)) return results;

  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      // Skip node_modules, .next, generated, etc.
      if (
        ["node_modules", ".next", "generated", "dist", "__tests__", "e2e", "test-results", "playwright-report", "database-backups"].includes(
          entry.name
        )
      ) {
        continue;
      }
      results.push(...walkDir(fullPath));
    } else if (FILE_EXTENSIONS.includes(path.extname(entry.name))) {
      results.push(fullPath);
    }
  }
  return results;
}

// ─── Main ────────────────────────────────────────────────────────────────────

function main() {
  const isDryRun = process.argv.includes("--dry-run");
  const allContexts: FileContext[] = [];

  console.log("🔍 Scanning for tagged files...\n");

  for (const scanDir of SCAN_DIRS) {
    const absDir = path.join(ROOT, scanDir);
    const files = walkDir(absDir);

    for (const file of files) {
      const content = fs.readFileSync(file, "utf-8");
      const tags = extractTags(content);

      if (Object.keys(tags).length > 0) {
        const relativePath = path.relative(ROOT, file).replace(/\\/g, "/");
        allContexts.push({ relativePath, tags });
      }
    }
  }

  console.log(`📄 Found ${allContexts.length} files with context tags.\n`);

  if (allContexts.length === 0) {
    console.log(
      "No tagged files found. Add @fileOverview, @stability, etc. to your files.\n"
    );
    console.log("Example:\n");
    console.log("/**");
    console.log(" * @fileOverview Root layout with auth session and providers");
    console.log(" * @stability stable");
    console.log(
      " * @dependencies auth.ts, @/components/providers/app-providers"
    );
    console.log(
      " * @keyInvariants Never import auth() in client components"
    );
    console.log(" */");
    return;
  }

  // Group by directory
  const grouped = new Map<string, FileContext[]>();
  for (const ctx of allContexts) {
    const dir = path.dirname(ctx.relativePath);
    const topDir = dir.split("/").slice(0, 2).join("/");
    if (!grouped.has(topDir)) grouped.set(topDir, []);
    grouped.get(topDir)!.push(ctx);
  }

  // Build markdown section
  let md = "\n\n<!-- @auto:start - Generated by scripts/aggregate-context.ts -->\n";
  md += `## Module Annotations (Auto-Generated)\n\n`;
  md += `> Last aggregated: ${new Date().toISOString().split("T")[0]}\n\n`;

  for (const [dir, contexts] of [...grouped.entries()].sort()) {
    md += `### ${dir}\n\n`;
    md += "| File | Overview | Stability |\n";
    md += "|------|----------|-----------|\n";

    for (const ctx of contexts.sort((a, b) =>
      a.relativePath.localeCompare(b.relativePath)
    )) {
      const fileName = path.basename(ctx.relativePath);
      const overview = ctx.tags.fileOverview || "—";
      const stability = ctx.tags.stability || "—";
      md += `| [${fileName}](${ctx.relativePath}) | ${overview} | ${stability} |\n`;
    }

    md += "\n";

    // Add detail blocks for files with extra tags
    for (const ctx of contexts) {
      const extraTags = Object.entries(ctx.tags).filter(
        ([k]) => k !== "fileOverview" && k !== "stability"
      );
      if (extraTags.length > 0) {
        const fileName = path.basename(ctx.relativePath);
        md += `<details><summary>${fileName} — details</summary>\n\n`;
        for (const [tag, value] of extraTags) {
          md += `- **@${tag}:** ${value}\n`;
        }
        md += `\n</details>\n\n`;
      }
    }
  }

  md += "<!-- @auto:end -->\n";

  if (isDryRun) {
    console.log("─── DRY RUN OUTPUT ───\n");
    console.log(md);
    console.log("─── END DRY RUN ───\n");
    return;
  }

  // Read existing MasterContext.md and replace or append auto section
  if (!fs.existsSync(MASTER_CONTEXT_PATH)) {
    console.error(`❌ MasterContext.md not found at ${MASTER_CONTEXT_PATH}`);
    process.exit(1);
  }

  let masterContent = fs.readFileSync(MASTER_CONTEXT_PATH, "utf-8");

  const autoStartMarker = "<!-- @auto:start";
  const autoEndMarker = "<!-- @auto:end -->";

  const startIdx = masterContent.indexOf(autoStartMarker);
  const endIdx = masterContent.indexOf(autoEndMarker);

  if (startIdx !== -1 && endIdx !== -1) {
    // Replace existing auto section
    masterContent =
      masterContent.substring(0, startIdx) +
      md.trim() +
      "\n" +
      masterContent.substring(endIdx + autoEndMarker.length);
  } else {
    // Append to end
    masterContent = masterContent.trimEnd() + "\n" + md;
  }

  fs.writeFileSync(MASTER_CONTEXT_PATH, masterContent, "utf-8");
  console.log(
    `✅ Updated MasterContext.md with ${allContexts.length} module annotations.\n`
  );
}

main();
